# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri Jun 14 16:07:13 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.table_notUsed = QtWidgets.QTableView(self.frame)
        self.table_notUsed.setObjectName("table_notUsed")
        self.gridLayout.addWidget(self.table_notUsed, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_assign = QtWidgets.QPushButton(self.frame)
        self.btn_assign.setObjectName("btn_assign")
        self.horizontalLayout.addWidget(self.btn_assign)
        self.btn_borrow = QtWidgets.QPushButton(self.frame)
        self.btn_borrow.setObjectName("btn_borrow")
        self.horizontalLayout.addWidget(self.btn_borrow)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_borrowed = QtWidgets.QTableView(self.tab)
        self.table_borrowed.setObjectName("table_borrowed")
        self.gridLayout_3.addWidget(self.table_borrowed, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.table_assigned = QtWidgets.QTableView(self.tab_2)
        self.table_assigned.setObjectName("table_assigned")
        self.gridLayout_5.addWidget(self.table_assigned, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_returnRemarks = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_returnRemarks.sizePolicy().hasHeightForWidth())
        self.lbl_returnRemarks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_returnRemarks.setFont(font)
        self.lbl_returnRemarks.setObjectName("lbl_returnRemarks")
        self.gridLayout_2.addWidget(self.lbl_returnRemarks, 0, 0, 1, 1)
        self.textedit_returnRemarks = QtWidgets.QPlainTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textedit_returnRemarks.sizePolicy().hasHeightForWidth())
        self.textedit_returnRemarks.setSizePolicy(sizePolicy)
        self.textedit_returnRemarks.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textedit_returnRemarks.setObjectName("textedit_returnRemarks")
        self.gridLayout_2.addWidget(self.textedit_returnRemarks, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_return_borrowed = QtWidgets.QPushButton(self.frame_2)
        self.btn_return_borrowed.setObjectName("btn_return_borrowed")
        self.horizontalLayout_2.addWidget(self.btn_return_borrowed)
        self.btn_destroyed_borrowed = QtWidgets.QPushButton(self.frame_2)
        self.btn_destroyed_borrowed.setObjectName("btn_destroyed_borrowed")
        self.horizontalLayout_2.addWidget(self.btn_destroyed_borrowed)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_ITClear_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_ITClear_dock.setObjectName("btn_ITClear_dock")
        self.gridLayout_4.addWidget(self.btn_ITClear_dock, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 9, 0, 1, 1)
        self.btn_newInventory_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_newInventory_dock.setObjectName("btn_newInventory_dock")
        self.gridLayout_4.addWidget(self.btn_newInventory_dock, 0, 0, 1, 1)
        self.line_currentUser_dock = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_currentUser_dock.setReadOnly(True)
        self.line_currentUser_dock.setObjectName("line_currentUser_dock")
        self.gridLayout_4.addWidget(self.line_currentUser_dock, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 7, 0, 1, 1)
        self.btn_newUnit_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_newUnit_dock.setObjectName("btn_newUnit_dock")
        self.gridLayout_4.addWidget(self.btn_newUnit_dock, 2, 0, 1, 1)
        self.btn_manageSuppliers_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_manageSuppliers_dock.setObjectName("btn_manageSuppliers_dock")
        self.gridLayout_4.addWidget(self.btn_manageSuppliers_dock, 5, 0, 1, 1)
        self.btn_logout_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_logout_dock.setObjectName("btn_logout_dock")
        self.gridLayout_4.addWidget(self.btn_logout_dock, 11, 0, 1, 1)
        self.btn_managePersons_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_managePersons_dock.setObjectName("btn_managePersons_dock")
        self.gridLayout_4.addWidget(self.btn_managePersons_dock, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 1)
        self.btn_manageRooms_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_manageRooms_dock.setObjectName("btn_manageRooms_dock")
        self.gridLayout_4.addWidget(self.btn_manageRooms_dock, 6, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "NOT USED", None, -1))
        self.btn_assign.setText(QtWidgets.QApplication.translate("MainWindow", "Assign", None, -1))
        self.btn_borrow.setText(QtWidgets.QApplication.translate("MainWindow", "Borrow", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "BORROWED", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "ASSIGNED", None, -1))
        self.lbl_returnRemarks.setText(QtWidgets.QApplication.translate("MainWindow", "Return Remarks", None, -1))
        self.btn_return_borrowed.setText(QtWidgets.QApplication.translate("MainWindow", "Return", None, -1))
        self.btn_destroyed_borrowed.setText(QtWidgets.QApplication.translate("MainWindow", "Destroyed", None, -1))
        self.btn_ITClear_dock.setText(QtWidgets.QApplication.translate("MainWindow", "IT Clear", None, -1))
        self.btn_newInventory_dock.setText(QtWidgets.QApplication.translate("MainWindow", "New Inventory", None, -1))
        self.btn_newUnit_dock.setText(QtWidgets.QApplication.translate("MainWindow", "New Unit", None, -1))
        self.btn_manageSuppliers_dock.setText(QtWidgets.QApplication.translate("MainWindow", "Manage Suppliers", None, -1))
        self.btn_logout_dock.setText(QtWidgets.QApplication.translate("MainWindow", "Logout", None, -1))
        self.btn_managePersons_dock.setText(QtWidgets.QApplication.translate("MainWindow", "Manage Person", None, -1))
        self.btn_manageRooms_dock.setText(QtWidgets.QApplication.translate("MainWindow", "Manage Rooms", None, -1))

